### PR TITLE
Add DJANGO_ENVIRONMENT variable

### PR DESCRIPTION
**Pull request by willkg**
This makes it easier to test for a test context and do test-specific
things.

Amongst other things, we can switch indexes for Elastic depending on whether we're running tests or not.

r?

### CODE REVIEW

**Comment by davedash** [comment]
I hate that this is the best way to do this.

**Comment by jbalogh** [comment]
Doesn't @davedash's settings_test allow for this?

**Comment by willkg** [comment]
I'm not sure how settings.py, settings_local.py and settings_test.py all work with each other and there's no documentation for settings_test that I could see.  I don't know if it solves the problem or not.

**Comment by peterbe** [comment]
r-

@willkg if you define a settings_test.py it'll override anything in `django.conf.settings`. So you could set: `RUNNING_TESTS = False` in your `settings/base.py` and in `settings_test.py` you set `RUNNING_TESTS = True`.

That's already what test-utils offer. Adding another way of doing it would cause confusion. Also, using django.conf.settings is the "standard" way to deciding environment differences. Introducing `os.environ` as another dimension just doesn't taste right. 

Mayhaps the issue here is in the documentation (or lack of) of `settings_test`.

**Comment by willkg** [comment]
I'm working on Kitsune and we don't have a settings/base.py.  We do have a settings.py and a settings_local.py the latter overrides settings in the former.  How does settings_test.py affect both of those?

**Comment by peterbe** [comment]
@willkg that doesn't matter. However you do it, once Django boots up it creates this global django.conf.settings object and populates it partly from your file imports and partly from various default values in django.

**Comment by jsocol** [comment]
@peterbe: FWIW, we already look at `os.environ` for `FORCE_DB`. It's theoretical at this point, but if there were things that depended on `TESTS_RUNNING`, then having a debugging tool like:

``` bash
$ TESTS_RUNNING=1 ./manage.py runserver
```

could be valuable. I think Will changed tacks here, anyway, but I just wanted to comment in defense of env vars for configuration.

**Comment by peterbe** [comment]
Fair point. That `FORCE_DB` trick does come in handy. Either way, I'd suggest we use settings as much as possible. Individual developers could have shortcuts such as

```
$ echo "import os;TESTS_RUNNING=os.environ.get('TESTS_RUNNING', '')" >> settings/local.py
```

**Comment by willkg** [comment]
Total ew to that echo line.

I'm nixing this pull request.  I can do what I need to with settings_test.  I'll write up some documentation on that for test-utils as a separate pull request.  Thanks everyone!

**Pull request closed without merging**
