### PR TITLE
Add a TestRunner that does not touch databases at all.

### PR DESCRIPTION
**Pull request by rik**
This is useful for the bedrock project.

### CODE REVIEW

**Comment by erikrose** [comment]
FWIW, I plan to add some smarts to django-nose so it won't bother setting up the DB if there are no subclasses of TransactionTestCase  among the selected tests.

**Comment by rik** [comment]
That would be a nicer way to solve this actually. But that's a blocker to run tests on bedrock, I'll still need this in the meantime.

**Comment by erikrose** [comment]
Yep, hence the "FWIW". :-)

**Comment by rik** [comment]
Who could help review this?

**Comment by davedash** [comment]
Rik do you still need this merged?

**Comment by rik** [comment]
Yes please.

**Pull request merged**
